language: swift
script: 
  - set -o pipefail
  - xcodebuild -project LinesSorter.xcodeproj -scheme "LinesSorterTests" -destination "platform=OS X,arch=x86_64" -configuration Debug build-for-testing
  - xcodebuild -project LinesSorter.xcodeproj -scheme "LinesSorterTests" -destination "platform=OS X,arch=x86_64" -configuration Debug test-without-building